_STRINGS = {
    "en": {
        "device": "Device",
        "save_device": "Save device",
        "saved_devices": "Saved devices",
        "mac_address": "MAC-address",
        "mac_hint": "XX:XX:XX:XX:XX:XX",
        "mac_helper": "Format: XX:XX:XX:XX:XX:XX\ne.g. AA:BB:CC:DD:EE:FF",
        "ip_or_broadcast": "IP or Broadcast",
        "ip_hint": "255.255.255.255",
        "port": "Port",
        "port_hint": "9",
        "device_name": "Device name",
        "device_name_hint": "e.g. Home PC",
        "device_group": "Group",
        "device_group_hint": "e.g. Office",
        "wake_up": "Wake Up",
        "wake_selected": "Wake selected",
        "selected": "selected",
        "clear_fields": "Clear fields",
        "send": "Sending...",
        "no_devices": "No saved devices yet",
        "no_devices_hint": "Add a device above and tap Save",
        "sort": "Sort",
        "sort_name": "By name",
        "sort_last_woken": "Last woken",
        "interface": "Interface",
        "interface_default": "Default (all)",
        "save": "Save",
        "delete_device": "Delete device",
        "delete_confirm": "Are you sure you want to delete this device?",
        "cancel": "Cancel",
        "delete": "Delete",
        "invalid_mac": "Invalid MAC format",
        "invalid_ip": "Invalid IP",
        "mac_required": "MAC address is required",
        "invalid_mac_format": "Invalid MAC format. Use XX:XX:XX:XX:XX:XX",
        "invalid_ip_format": "Invalid IP address format",
        "ip_not_private": "Only local network IPs allowed (10.x, 172.16-31.x, 192.168.x)",
        "port_must_be_number": "Port must be a number",
        "port_range": "Port must be between 1 and 65535",
        "mac_valid_required": "Enter a valid MAC before saving",
        "name_required": "Enter a device name",
        "mac_sent": "Magic packet sent to",
        "network_error": "Network error",
        "timeout_error": "Timeout after",
        "deleted": "Deleted",
        "saved": "Saved",
        "woke": "Woke",
        "just_now": "just now",
        "min_ago": "m ago",
        "hour_ago": "h ago",
        "day_ago": "d ago",
        "failed": "failed",
        "woke_count": "Woke {ok}/{total} devices",
        "woke_count_fail": "Woke {ok}/{total} devices, {fail} failed",
        "select_group": "All groups",
        "log_viewer": "Log viewer",
        "log_empty": "No log entries",
        "language": "Language",
        "no_interface": "Default",
    },
    "ru": {
        "device": "Устройство",
        "save_device": "Сохранить устройство",
        "saved_devices": "Сохранённые устройства",
        "mac_address": "MAC-адрес",
        "mac_hint": "XX:XX:XX:XX:XX:XX",
        "mac_helper": "Формат: XX:XX:XX:XX:XX:XX\nнапример AA:BB:CC:DD:EE:FF",
        "ip_or_broadcast": "IP или Broadcast",
        "ip_hint": "255.255.255.255",
        "port": "Порт",
        "port_hint": "9",
        "device_name": "Имя устройства",
        "device_name_hint": "например Домашний ПК",
        "device_group": "Группа",
        "device_group_hint": "например Офис",
        "wake_up": "Разбудить",
        "wake_selected": "Разбудить выбранные",
        "selected": "выбрано",
        "clear_fields": "Очистить поля",
        "send": "Отправка...",
        "no_devices": "Нет сохранённых устройств",
        "no_devices_hint": "Добавьте устройство выше и нажмите Сохранить",
        "sort": "Сортировка",
        "sort_name": "По имени",
        "sort_last_woken": "Последний запуск",
        "interface": "Интерфейс",
        "interface_default": "По умолчанию",
        "save": "Сохранить",
        "delete_device": "Удалить устройство",
        "delete_confirm": "Вы уверены, что хотите удалить это устройство?",
        "cancel": "Отмена",
        "delete": "Удалить",
        "invalid_mac": "Неверный формат MAC",
        "invalid_ip": "Неверный IP",
        "mac_required": "MAC-адрес обязателен",
        "invalid_mac_format": "Неверный формат MAC. Используйте XX:XX:XX:XX:XX:XX",
        "invalid_ip_format": "Неверный формат IP-адреса",
        "ip_not_private": "Только локальные IP (10.x, 172.16-31.x, 192.168.x)",
        "port_must_be_number": "Порт должен быть числом",
        "port_range": "Порт должен быть от 1 до 65535",
        "mac_valid_required": "Введите корректный MAC перед сохранением",
        "name_required": "Введите имя устройства",
        "mac_sent": "Magic-пакет отправлен на",
        "network_error": "Ошибка сети",
        "timeout_error": "Таймаут",
        "deleted": "Удалено",
        "saved": "Сохранено",
        "woke": "Разбужен",
        "just_now": "только что",
        "min_ago": "м назад",
        "hour_ago": "ч назад",
        "day_ago": "д назад",
        "failed": "ошибок",
        "woke_count": "Разбужено {ok}/{total} устройств",
        "woke_count_fail": "Разбужено {ok}/{total}, {fail} с ошибками",
        "select_group": "Все группы",
        "log_viewer": "Журнал",
        "log_empty": "Нет записей в журнале",
        "language": "Язык",
        "no_interface": "По умолчанию",
    },
}


def get_strings(lang: str) -> dict[str, str]:
    return _STRINGS.get(lang, _STRINGS["en"])
